version: '3.11'

services:
  web:
    build: .
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    command: >
      sh -c "python3 manage.py makemigrations &&
             python3 manage.py migrate &&
             python3 manage.py runserver 0.0.0.0:8000"
    env_file:
      - .env

  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: sof
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 2710
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  postgres_data:
