version: '3.11'

services:
  web:
    build: .
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    command: >
      sh -c "pip install -r requirements.txt &&
             python3 manage.py makemigrations &&
             python3 manage.py migrate &&
             python3 manage.py runserver 0.0.0.0:8000"
    # environment:
    #   POSTGRES_HOST: db  # Use the service name defined below
    # depends_on:
    #   - db
    # networks:
    #   - app_network

#   db:
#     image: postgres:latest
#     environment:
#       POSTGRES_DB: sof
#       POSTGRES_USER: postgres
#       POSTGRES_PASSWORD: 2710
#     volumes:
#       - postgres_data:/var/lib/postgresql/data
#     ports:
#       - "5432:5432"
#     networks:
#       - app_network

# volumes:
#   postgres_data:

# networks:
#   app_network:
#     driver: bridge
